import { useEffect } from "react";
import "./LegalPage.css";

const APP_DOMAIN = "sightsinger.app";
const APP_BRAND_DOMAIN = "SightSinger.app";
const PRIVACY_EMAIL = `privacy@${APP_DOMAIN}`;

export default function LegalPrivacy() {
  useEffect(() => {
    document.body.classList.add("legal-active");
    return () => {
      document.body.classList.remove("legal-active");
    };
  }, []);

  return (
    <main className="legal-page">
      <h1>Privacy Policy</h1>
      <p className="legal-updated">Last updated: 2026-01-26</p>

      <p>
        This Privacy Policy explains how {APP_BRAND_DOMAIN} ("we", "us", "our")
        collects, uses, and protects personal data when you use {APP_BRAND_DOMAIN}
        (the "Service"). We comply with the UK GDPR and the EU GDPR where
        applicable.
      </p>

      <h2>1. Controller</h2>
      <p>
        {APP_BRAND_DOMAIN} is the data controller for personal data processed through the Service.
      </p>

      <h2>2. Personal Data We Collect</h2>
      <ul>
        <li>Account data: email address, display name, and authentication identifiers.</li>
        <li>Usage data: interactions with the Service, session metadata, and error logs.</li>
        <li>Uploaded content: MusicXML files and metadata required to render audio.</li>
        <li>Generated outputs: audio generated by the Service.</li>
        <li>Technical data: IP address, device/browser information, and App Check tokens.</li>
      </ul>

      <h2>3. Legal Bases (UK/EU GDPR)</h2>
      <ul>
        <li>Contract: to provide the Service and features you request.</li>
        <li>Legitimate interests: to improve, secure, and monitor the Service.</li>
        <li>Consent: where you opt in to communications (e.g., waiting list).</li>
        <li>Legal obligations: where required by law.</li>
      </ul>

      <h2>4. How We Use Data</h2>
      <ul>
        <li>Provide and operate the Service.</li>
        <li>Authenticate users and protect against abuse.</li>
        <li>Process uploads and generate audio.</li>
        <li>Communicate with you about your account or requested services.</li>
        <li>Improve reliability and performance.</li>
      </ul>

      <h2>5. Sharing and Processors</h2>
      <p>
        We do not sell your personal data. We may share data with trusted
        processors that help operate the Service (e.g., hosting, analytics,
        email delivery). These processors are bound by confidentiality and data
        protection obligations.
      </p>

      <h2>6. International Transfers</h2>
      <p>
        If personal data is transferred outside the UK/EU, we use appropriate
        safeguards (such as Standard Contractual Clauses) where required.
      </p>

      <h2>7. Data Retention</h2>
      <p>
        We retain personal data only as long as necessary for the purposes
        described in this policy, or as required by law. You may request
        deletion of your account data.
      </p>

      <h2>8. Security</h2>
      <p>
        We implement technical and organisational measures to protect your data,
        including access controls and encryption where appropriate. No system is
        100% secure, and we cannot guarantee absolute security.
      </p>

      <h2>9. Your Rights (UK/EU GDPR)</h2>
      <ul>
        <li>Access, correct, or delete your personal data.</li>
        <li>Object to or restrict processing.</li>
        <li>Port your data.</li>
        <li>Withdraw consent at any time (where processing is based on consent).</li>
        <li>Lodge a complaint with a supervisory authority.</li>
      </ul>

      <h2>10. Cookies and Similar Technologies</h2>
      <p>
        We use essential cookies and local storage for authentication and session
        management. We also use analytics cookies to understand how the Service
        is used. Where required by law (including EU/UK), we will only enable
        analytics cookies after you provide consent via our cookie banner.
      </p>

      <h2>11. Children's Privacy</h2>
      <p>
        The Service is not intended for children under the minimum age required
        by law. We do not knowingly collect data from children.
      </p>

      <h2>12. Updates to This Policy</h2>
      <p>
        We may update this policy from time to time. The "Last updated" date
        indicates the latest revision.
      </p>

      <h2>13. Contact</h2>
      <p>For privacy requests or questions, contact {PRIVACY_EMAIL}.</p>

      <p className="legal-disclaimer">
        This document is provided for general informational purposes and does
        not constitute legal advice.
      </p>
    </main>
  );
}
