voicebanks:
#  - id: Hoshino Hanami v1.0
#    gender: female
#    voice_type: soprano
  - id: UFR-V1.0
    gender: female
    voice_type: soprano
  - id: Katyusha_v170
    gender: female
    voice_type: soprano
  - id: Keiro_Revenant_v170
    gender: male
    voice_type: bass
  - id: Liam_Thorne_v170
    gender: male
    voice_type: tenor
  - id: PM-31_Commercial_Indigo
    gender: male
    voice_type: tenor
  - id: PM-31_Commercial_Scarlet
    gender: male
    voice_type: tenor
  - id: SAiFA_v170
    gender: female
    voice_type: alto
